---
- name: Check if Apache2 service exists
  stat: path=/etc/init.d/apache2
  register: apache2_status

- name: Disable Apache2 service if exists
  service: name=apache2 state=stopped enabled=no
  when: apache2_status.stat.exists == True

- name: Install nginx
  apt:
    name: nginx
    state: present
