---
- name: Deploy server
  hosts: all
  become: yes
  become_method: sudo
  roles:
   - update
   - utility
   - nginx
   - php
   - postgresql
   - webserver
  vars:
    dbname: app
    dbuser: app
    dbpassword: 123456
